### ISSUE TITLE
MariaDB does not recover from HASS.io backup

### ISSUE THREAD

**Issue by Spirituss** [home-assistant/addons#1353]
**Home Assistant release with the issue:**

Home Assistant 0.110.2

**Last working Home Assistant release (if known):**
Unknown (but it definitely worked earlier).

**Operating environment (Hass.io/Docker/Windows/etc.):**

Hass.io/Docker/Supervised

**Component/platform:**

MariaDB add-on used as record/history component.

**Description of problem:**
After recovery from Hass.io snapshot MariaDB doesn't work any more. The only way to force it to work is to uninstall the add-on and install it again with the same settings. Of course, in this case you lose your DB and history.

**Problem-relevant configuration.yaml entries and (fill out even if it seems unimportant):**

```
recorder: 
  db_url: mysql://hass:password@192.168.xxx.xxx/homeassistant?charset=utf8
  purge_interval: 7
  purge_keep_days: 7
```

**Traceback (if applicable):**

**Additional information:**
It worked fine on one of earlier version of hass.io. There are other issues containing relevant information that were closed without a solution:
https://github.com/home-assistant/core/issues/26152
https://github.com/home-assistant/hassio-addons/issues/667
