### ISSUE TITLE
The RPC Shutdown-addon is not working and no logs are being generated.

### ISSUE THREAD

**Issue by deryckhans** [home-assistant/addons#1593]
## The problem
The RPC shutdown-addon installs fine, and is started without errors.  It is unfortunatly not working at all, and no logs are being generated.  

## Environment

- Add-on with the issue: **RPC Shutdown**
- Add-on release with the issue:  **2.2** 
- Last working add-on release (if known):  **unknown**
- Operating environment (OS/Supervised):  **HassOS 4.13  / Supervisor 245**
--

## Problem-relevant configuration

```
computers:
  - alias: test-pc
    address: 192.168.0.1
    credentials: user%password
    delay: 0
    message: >-
      Home Assistant is shutting down this PC. This cannot be canceled. Please
      save your work!

```

## Traceback/Error logs

No logs are being generated.  

![image](https://user-images.githubusercontent.com/71820266/94136251-f2af9780-fe64-11ea-975d-bc3c4b95ef5c.png)

```txt

```
