### ISSUE TITLE
LetsEncrypt won't start. Immediately fails and refers to log.  Log is empty.

### ISSUE THREAD

**Issue by dethpickle** [home-assistant/addons#1598]
## The problem

What was a normally working LetsEncrypt with DNS (cloud flare) has now failed to start.  "Failed to start addon
Unknown error, see logs". The add-on log is empty. The home assistant log doesn't show anything around the time I tried to start the add-on.

I've tried uninstalling and reinstalling the add-on to no avail.

## Environment

- Add-on with the issue:  Lets Encrypt 
- Add-on release with the issue: 4.10.0
- Last working add-on release (if known): unknown
- Operating environment (OS/Supervised): Hassio 0.115.3,  OS 5.4.63, Supervisor 245

## Problem-relevant configuration

```yaml
email: my email
domains:
  - '*.mydomain.com'
certfile: fullchain.pem
keyfile: privkey.pem
challenge: dns
dns:
  provider: dns-cloudflare
  cloudflare_email: my email
  cloudflare_api_key: mike

```

## Traceback/Error logs

no logs to provide

## Additional information
From looking around, I don't see anyone reporting anything similar.  I've got to figure is a problem just for me.  But, I can't think of a place where I could have caused an issue.  I really more surprised at nothing in the logs.
The failure is really instantaneous - right when you hit Start.
