### ISSUE TITLE
Error 217#217 in Hassio log

### ISSUE THREAD

**Issue by phoxy84** [home-assistant/addons#1599]
I have Homeassistant (115.3) running with DuckDNS and NGINX Home Assistant SSL proxy (v3.0.1). It's running fine but I have some errors in my logfiles. What can be wrong and how can I fix this? Thanks.

```
[13:20:45] INFO: Running nginx...
2020/09/28 10:15:37 [error] 217#217: *2442 connect() failed (111: Connection refused) while connecting to upstream, client: XXX.XXX.XXX.XXX, server: *private*.duckdns.org, request: "GET /api/websocket HTTP/1.1", upstream: "http://XXX:8123/api/websocket", host: "*private*.duckdns.org"

```

My config is:
```
domain: *private*.duckdns.org
certfile: fullchain.pem
keyfile: privkey.pem
hsts: max-age=31536000; includeSubDomains
cloudflare: false
customize:
  active: false
  default: nginx_proxy_default*.conf
  servers: nginx_proxy/*.conf

```
