### ISSUE TITLE
Google Assistant SDK creates an additional speaker on every restart

### ISSUE THREAD

**Issue by mrmessy** [home-assistant/addons#1614]
## The problem

Google Assistant SDK creates a new speaker on every restart.
As far as I can tell it is because the /data/device.json file is not persistant.
From the code: the last device id should prevent a new speaker being created.
https://github.com/home-assistant/hassio-addons/blob/091f8de99b3d38ba94604355415d9dc5fe26c144/google_assistant/rootfs/usr/bin/hassio_gassistant.py#L72

When I connect to the docker container the device.json file changes on a restart. eg
{"last_device_id": "F00FFFBEE327C6A8B44F2A480E917540",
changes to
{"last_device_id": "F2595A532DF8FAA47E41D45557DCECC6",
and an extra new device is created without removing the old one.

## Environment

- Add-on with the issue: Google Assistant SDK
- Add-on release with the issue: 2.5.0
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): HassOS 4.13 on RPI 4

## Problem-relevant configuration

configuration.yaml
```yaml

google_assistant:
  project_id: home-ass-BLAHBLAH
  service_account: !include "Home Ass-BLAHBLAH.json"
  report_state: true
```
Google Assistant SDK settings
```yaml
client_secrets: >-
  client_secret_BLAHBLAH.apps.googleusercontent.com.json
project_id: home-ass-speaker
model_id: home-ass-speaker-home-ass-speaker-BLAHBLAH
feedback:
  enable: true
  volume: 100
```

## Traceback/Error logs

```txt

```
