### ISSUE TITLE
Deconz 6.5.0 fails to recognize RaspBee

### ISSUE THREAD

**Issue by nilsmau** [home-assistant/addons#1682]
## The problem

After updating Deconz Add On from 6.4.1 to 6.5.0 Deconz fails to recognize the RaspBee, even though the configuration has not changed.
`device: /dev/ttyS0`

## Environment

- Add-on with the issue: Deconz
- Add-on release with the issue: 6.5.0
- Last working add-on release (if known): 6.4.1
- Operating environment (OS/Supervised): HassOS 5.4 (dev), Supervisor 2020.11.0 (stable)
- Home Assistant 0.117.6
- Hardware: Raspberry Pi 4, SSD via USB (no SD card)

## Problem-relevant configuration

```yaml
device: /dev/ttyS0
vnc_password: omitted
dbg_info: 1
dbg_aps: 1
dbg_otau: 1
dbg_zcl: 1
dbg_zdp: 1
```

## Traceback/Error logs

Deconz error shows:
```txt
device state timeout ignored in state 2
```

## Additional information
Nothing else was changed, and reverting back to 6.4.1 fixed the issue.
