### ISSUE TITLE
Microsoft VS code

### ISSUE THREAD

**Issue by Cheerion** [home-assistant/addons#1688]
## The problem

  I use the approach with packages to keep my configuration.yaml clean. 
Since some time the Microsoft Visual Code add-on highlights piece of code in red with the message 'Incorrect type. Expected "Object".' underneath the highlighted block of text.

It happens with scripts and input_selects. Automations (f.e.) run without this highlighted text. 

When I run the config checker, no errors are mentioned.

## Environment
  Home Assistant 0.118.1

- Add-on with the issue: Microsoft Visual Code
- Add-on release with the issue: 2.8.2
- Last working add-on release (if known): I don't know
- Operating environment (OS/Supervised): Supervised

## Problem-relevant configuration
configuration.yaml
 ```yaml
homeassistant:
  # Load packages
  packages: !include_dir_named integrations
```

Directory integrations has a script.yaml file:
```yaml
script: !include_dir_named ../scripts
```

In the scripts folder, I have several files that show encouter the bug mentioned above. An example:
```yaml
---
alias: Speel radiostation op media player naar keuze
description: Play radio station on media player
mode: single
sequence:
  - service: media_player.volume_set
    data:
      entity_id: media_player.google_home_huiskamer
      volume_level: "0.25"
  - service: media_player.play_media
    data:
      media_content_id: https://s43.myradiostream.com/18192/listen.mp3
      media_content_type: audio/mp4
      entity_id: media_player.google_home_huiskamer
```
The highlighted text starts at the first service entry. Underneath that last line, Incorrect type. Expected "Object" is mentioned.

```yaml

```

## Traceback/Error logs

```txt

```
