### ISSUE TITLE
homematic: OCCU version is outdated

### ISSUE THREAD

**Issue by awillecke** [home-assistant/addons#1694]
## The problem
The version of the OCCU is quite old by now (3.51.6-1 released on 10.02.2020). The most recent version [3.55.5-1](https://github.com/jens-maus/occu/tags) was released at the beginning of December. Due to the old version, newer devices (such as HmIP-WRCC2) might not be recognized and cannot be used with this addon.

Thank you.

## Environment

- Add-on with the issue: homematic
- Add-on release with the issue: 10.3
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): Supervised

## Problem-relevant configuration

```yaml
rf_enable: false
wired_enable: false
hmip_enable: true
rf:
  - type: CCU2
    device: /dev/AMA0
wired:
  - serial: xy
    key: abc
    ip: 192.168.0.9
hmip:
  - type: HMIP_CCU2
    device: /dev/ttyUSB0
regahss_reset: false

```

## Traceback/Error logs

```txt
[WARN] HMIPNetworkManagementHandler - AP 3014F711A000041709AD****: No device description found for manufacturer code: 1 device type 431 sgtin 3014F711A0002C1BE999****
```
