### ISSUE TITLE
Duck DNS in combination with UniFy Protect, Fibaro and Google cast

### ISSUE THREAD

**Issue by WilcoakaSIRB** [home-assistant/addons#1701]
## The problem

I installed Duck DNS to have my Duck DNS with HTTPS (needed for google cast). Got Duck DNS working folowing the installation guide (also the HTTP part). Reset HA and yes i could only start HA with https://ip adres/. So i was thinking glad that worked but then the problems started:
- Unify protect (camera's and doorbel) did not work anymore
- HA app did not work anymore (not with https://ip nor with https://myadress.duckdns.org nor without https:)
- Fibaro devices don't work anymore

I think its because the app changes IP adress (in my i think computer IP adress in). The moment i delete the Duck DNS app and change duck dns ip adress to HA ip everything starts working again (including the duck dns link) but because i deleted duck dns the app i still dont have a https link for my cast..

## Environment

- Add-on with the issue: Duck DNS
- Add-on release with the issue:  Current version: 1.12.4
- Last working add-on release (if known): unknown
- Operating environment (OS/Supervised): HA  0.118.4

## Problem-relevant configuration

allready deleted but it was:
```yaml
lets_encrypt:
  accept_terms: true
  certfile: fullchain.pem
  keyfile: privkey.pem
token: from the site
domains:
  - ....duckdns.org/
aliases: []
seconds: 300


and in file editor: 
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
```

## Traceback/Error logs

```txt

```
