### ISSUE TITLE
let's encrypt addon accepts multiple domains but only copies one

### ISSUE THREAD

**Issue by DanielStefanK** [home-assistant/addons#1706]
## The problem
When I run the addon only one of the requested and created certs is being copied to the ssl folder. Instead all created/Live certificates and keys should be copied to the ssl folder.

## Environment
add multiple domains to the domain parameter.
i.e.:
```yaml
domains:
  - c1.my-domain.tld
  - c2.my-domain.tld
```
- Add-on with the issue: Let's Encrypt
- Add-on release with the issue:  4.11.0
- Last working add-on release (if known):  - 
- Operating environment (OS/Supervised):  HassOS 4.16 on Raspberry Pi 3 b+

## Problem-relevant configuration
```yaml
email: "example@example.com"
domains:
  - c1.my-domain.tld
  - c2.my-domain.tld
certfile: fullchain.pem
keyfile: privkey.pem
challenge: http
dns: {}

```

## Traceback/Error logs
_No errors_
