### ISSUE TITLE
Homematic Addon doesnt persist changes

### ISSUE THREAD

**Issue by Robbilie** [home-assistant/addons#1709]
## The problem
I am currently setting up the homematic addon. I have the PCB and the USB stick working after a hassle. Then i setup my devices, about 15. Now every time the addon restarts i end up with about 9 in their initial states while 6 appear in the inbox. Any configuration i make seems to be lost after a container restart. I havent seen any errors in the container logs so far.

## Environment
Latest Addons, Supervisor, Core and HassOS version. A mix of IP and non IP devices, the devices successfully configured and the devices iin the inbox seem to be a mix aswell.

- Add-on with the issue: Homematic
- Add-on release with the issue: 10.3
- Last working add-on release (if known): ~
- Operating environment (OS/Supervised): HassOs

## Problem-relevant configuration
```yaml
rf_enable: true
wired_enable: false
hmip_enable: true
rf:
  - type: CCU2
    device: /dev/ttyAMA0
wired:
  - serial: xy
    key: abc
    ip: 192.168.0.0
hmip:
  - type: HMIP_CCU2
    device: /dev/ttyUSB0
regahss_reset: false

```

## Traceback/Error logs

```txt

```
