### ISSUE TITLE
hm_ip.sh exit 1

### ISSUE THREAD

**Issue by DunklerPhoenix** [home-assistant/addons#1723]
## The problem
hm_ip.sh exists with exit 1.

## Environment

- Add-on with the issue: HomeMatic CCU
- Add-on release with the issue: 11.0.4
- Last working add-on release (if known): X
- Operating environment (OS/Supervised): Hassio 5.8 | Supervised 2020.12.7 | HA Blue

## Problem-relevant configuration

```yaml
rf_enable: false
wired_enable: false
hmip_enable: true
rf:
  - type: CCU2
    device: >-
      /dev/serial/by-id/usb-Silicon_Labs_eQ-3_HmIP-RFUSB_3014XXXXXXXXXXXXXXXX-if00-port0
wired:
  - serial: abc
    key: abc
    ip: 10.0.0.0
hmip:
  - type: HMIP_CCU2
    device: >-
      /dev/serial/by-id/usb-Silicon_Labs_eQ-3_HmIP-RFUSB_3014XXXXXXXXXXXXXXXX-if00-port0
regahss_reset: false

```

## Traceback/Error logs

```txt
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] certs.sh: executing... 
Generating a RSA private key
.........................................+++++
................+++++
writing new private key to '/etc/config/server.pem'
-----
[cont-init.d] certs.sh: exited 0.
[cont-init.d] env.sh: executing... 
[cont-init.d] env.sh: exited 0.
[cont-init.d] hm_ip.sh: executing... 
[19:32:17] INFO: Setup HmIP-RF
[cont-init.d] hm_ip.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] hmip.sh: executing... 
[cont-finish.d] hmip.sh: exited 0.
[cont-finish.d] regahss.sh: executing... 
[cont-finish.d] regahss.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

## Additional information
https://ch.elv.com/elv-homematic-ip-arr-bausatz-rf-usb-stick-fuer-alternative-steuerungsplattformen-hmip-rfusb-fuer-smart-home-hausautomation-152306
