### ISSUE TITLE
HomeMatic Ingress Error 404

### ISSUE THREAD

**Issue by DunklerPhoenix** [home-assistant/addons#1725]
## The problem

The interface of HomeMatic is via ingress not reachable (error 404). If I expose the port 80 of the addon (in my case to port 900) I can reach the interface

## Environment

- Add-on with the issue: HomeMatic CCU
- Add-on release with the issue: 11.0.4
- Last working add-on release (if known): X
- Operating environment (OS/Supervised): Hassio 5.8 | Supervised 2020.12.7 | HA Blue

## Problem-relevant configuration

```yaml
rf_enable: false
wired_enable: false
hmip_enable: true
rf:
  - type: CCU2
    device: /dev/ttyUSB0
wired:
  - serial: xy
    key: abc
    ip: 192.168.0.0
hmip:
  - type: HMIP_CCU2
    device: /dev/ttyUSB0
regahss_reset: false

```

## Traceback/Error logs

```txt
172.30.32.2 - - [20/Dec/2020:04:11:18 +0100] "GET / HTTP/1.1" 200 1116 "https://XXX/hassio/ingress/core_homematic" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.50 Safari/537.36"
172.30.32.2 - - [20/Dec/2020:04:11:18 +0100] "GET /pages/index.htm&client=3 HTTP/1.1" 302 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.50 Safari/537.36"
172.30.32.2 - - [20/Dec/2020:04:11:18 +0100] "GET /pages/index.htm?sid=@s79gt8r8vN@ HTTP/1.1" 404 256 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.50 Safari/537.36"
```
