### ISSUE TITLE
ssh add-on: "ports": {     "22/tcp": null   },

### ISSUE THREAD

**Issue by jwilleke** [home-assistant/addons#1739]
## Nothing describes the Ports Settings

Configuration Page shows:
Container | Host | Description
-- | -- | --
22/tcp |   |  

But no idea what Host or Description of what  values should be.
I tried enabled (as the value shows as lightly shaded disabled but still get:

```[06:53:30] WARNING: SSH port is disabled. Prevent start of SSH server.```

Also, one would expect that typical Yaml for an array is like:
[ "ssh-rsa 1...", "ssh-rsa 2..." ]
or 
[ 
- "ssh-rsa 1..."
- "ssh-rsa 2..."
]

Yet I see:
- >-
  - >-
    ssh-rsa
    AAA...==
    jim@example.com

No brackets or quotes.

## Environment

- Add-on with the issue: ssh add-on
- Add-on release with the issue:   8.10.0
- Last working add-on release (if known): first time using
- Operating environment (OS/Supervised): 

## Problem-relevant configuration

```yaml
authorized_keys:
  - >-
    ssh-rsa
    AAA...==
    jim@example.com
password: contentsuppressed
server:
  tcp_forwarding: false
```

## Traceback/Error logs

```txt
[06:53:30] WARNING: SSH port is disabled. Prevent start of SSH server.
```
