### ISSUE TITLE
Mqtt official broker problems with ESP sending messages ?

### ISSUE THREAD

**Issue by zambujal** [home-assistant/addons#1747]
## The problem
 From maybe 2018, since I start using hassio, many/many sd card ago... :D I had allways some collapse ... and consequence sd card getting corrupted...  sometime it survived 3-4 weeks... not good enough.  The card get corrupted, because at the distance, I make an off/on with an switch remote from tuya... normally nothing happens, all went well... sometimes corruption...

Several times I thought I was getting hacked or something... but this happens even without connection with the outside... none whatsoever... mosquitto getting of the line, not doing anything ... not doing the work of broker... that is.

## Environment

I use the ESP 8266 coded with the normal libraries to connect to the mqtt broker of hassio the mosquitto one... to send the data from my arduino (connected via serial with an arduino)... and zigbee2mqtt on top, I had many weeks of good service... though... this mqtt broker never was stable enough. several times it survived weeks... sometimes just hours.

Then, just a few days ago, Again...I even had to the change the sdd card.... again... and said... enough... 1 terabit hard disc to the raspberry with a nicely 5 amp power source... with an usb extension charged from outside...

The MQTT disconnects from everything, don't restart (zigbee doesn't do anything anymore it needs the broker)... but the hassio enviroment, works nicely. 

could be the ESP connected  though the mqtt that works bad? (ite sends some weird stuff to the broker that makes him... sleep?!?) inconsistent? not every time, but sometimes...
 it's weird that it's only me?

I never was able to put more than 30 zigbee sensors (I have a lot more mind you not only zigbee or mqtt... the system after 2-3 weeks get corrupted, and I had to do an fresh resinstall... I was lasy to make an copy of this... my system never progressed like I wanted. But now it's a lot more "consistent" (with the failures)... I even was able to replicate this with an i386 machine with hassio (virtual machine with 8 gigas of ram ...more than the riny raspberry)
- Add-on with the issue: **MQTT official broker**
- Add-on release with the issue: **Every single one ... worse now...** (maybe because of more stuff on my side)
- Last working add-on release (if known): **I believe this never worked ok...** it's just worse when I put more stuff.
- Operating environment (OS/Supervised): hassio for i386 and hassio for the rasppberry pi3

## Problem-relevant configuration
 When I put  just the mosquitto in there with receving both zigbee2mqtt and the esp messages ( I don't believe it's the zigbee2mqtt... but my ESP...

```yaml
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
http:
  server_port: xxxxx
octoprint:
  host: xxxxxx
  api_key: xxxxx
mqtt:
  discovery: true
  discovery_prefix: homeassistant
sensor:  
  - platform: mqtt
    name: "Temperature sump"
    state_topic: "sensor/Temperatura Sump"
    unit_of_measurement: '°C'
  - platform: mqtt
    name: "Humidade sump"
    state_topic: "sensor/Humidade sump"
    unit_of_measurement: '%'
    icon: mdi:water-percent
  - platform: mqtt
    name: "Temperatura água"
    state_topic: "sensor/Temperatura água"
    unit_of_measurement: '°C'
    icon: mdi:coolant-temperature
  - platform: mqtt
    name: "Condutividade água osmose"
    state_topic: "sensor/tdsValue"
    unit_of_measurement: '°'
    icon: mdi:water
  - platform: mqtt
    name: "Estado"
    state_topic: "sensor/estado"
  - platform: mqtt
    name: "Potência Violeta"
    state_topic: "sensor/Potência luz"
    unit_of_measurement: '%'
  - platform: mqtt
    name: "Potência Branco"
    state_topic: "sensor/Potência luz2"
    unit_of_measurement: '%'
  - platform: mqtt
    name: "Potência Azul"    
    state_topic: "sensor/Potência luz3"
    unit_of_measurement: '%'
  - platform: mqtt
    name: "Horas"
    state_topic: "sensor/Horas"
  - platform: mqtt
    name: "Minutos"
    state_topic: "sensor/Minutos"
  - platform: mqtt
    name: "Segundos"    
    state_topic: "sensor/Segundos"
  - platform: mqtt
    name: "Bomba de reposição"
    state_topic: "sensor/Bomba de reposição"
  - platform: mqtt
    name: "Frasco escumador"    
    state_topic: "sensor/frasco escumador"
  - platform: mqtt
    name: "pH água"    
    state_topic: "sensor/pH água"
    unit_of_measurement: 'º'
    icon: mdi:test-tube
  - platform: enphase_envoy
    name: enphase_new
#     username: xxxxxx
#     password: xxxx
    ip_address: xxxxxxx
    scan_interval: 30
    monitored_conditions:
      - production
      - consumption
      - daily_production
      - seven_days_production
      - lifetime_production
      - inverters
      # Calculate Remaining Power
  - platform: template
    sensors:
      remaining_power:
        value_template: >
          {{ '%0.1f' | format(states('sensor.enphase_newenvoy_current_energy_consumption') | float - 
                              states('sensor.enphase_newenvoy_current_energy_production') | float) }}
        unit_of_measurement: 'W'
        friendly_name: Energia importada
switch:
  - platform: mqtt
    name: "Tasmota"
    state_topic: "stat/tasmota/RESULT"  
    value_template: "{{ value_json.POWER }}"
    command_topic: "cmnd/tasmota/POWER"
    payload_on: "ON"
    payload_off: "OFF"
    availability_topic: "tele/tasmota/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    retain: false
```

## Traceback/Error logs

```txt

```

## Additional information

And then I start using the mqtt that you are going to remove from the add-on ... the mqtt server and web client addon... everything FINE ok, just after 2-3 days... (fingers crossed) but after I gained courage to put the mosquitto... all went... bad again! So it's the mosquito, and if I am one of the few, I bet something from the ESP, that this mosquito doesnt't like... I could put also the code of the esp for you to see... this is really weird... why the other mqtt server works nicely... I don't really now...

I have an similar post that Frenk closed, but I was on wrong assumptions... now I tested it a lot more... My idea is that with this "old" mqtt broker, I will never  be bad... if you erased this... I might have to go to the non hassio enviroment... to get an mqtt that works...
