### ISSUE TITLE
HA not reachable with local IP after activating DuckDNS

### ISSUE THREAD

**Issue by SirFiChi** [home-assistant/addons#1754]
## The problem
I installed DuckDNS and configured it. After activating and Updating the HA-Core I spent about 2 hours to "repair" my installation over HDMI-console because HA wasn't reachable over local IP anymore.

I also had the problem, that I changed the DuckDNS config to write the ssl files in other folders. This failed and I had to choose another subdomain from duckdns.org... -.-

After all I figured out, that my installation is only reachable over the external address.

1. Is there a way to activate the local address again?
2. How to solve this if the connection to the provider stops and the external address isn't available?
3. If there is an actual solution, can someone add this to the documentation?

Thanks for your help.

## Environment
- Raspi 3B
- DuckDNS 1.12.4 
- Supervisor Version 2020.12.7 
- OS: Home Assistant OS 5.10

- Add-on with the issue:
- Add-on release with the issue: 
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): 

## Problem-relevant configuration
DuckDNS Config:
```
lets_encrypt:
  accept_terms: true
  certfile: fullchain.pem
  keyfile: privkey.pem
token: XXXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXXX
domains:
  - XXXXXXX.duckdns.org
aliases: []
seconds: 300
```

```yaml
[...]
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
[...]
```

## Traceback/Error logs

```txt

```
