### ISSUE TITLE
Samba share fills up it's log with continuously repeating entry

### ISSUE THREAD

**Issue by lmagyar** [home-assistant/addons#1758]
## The problem

In each ~10 second the same line is written in the log:
>added interface lo ip=::1 bcast= netmask=ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff

It seems to be IPv6 related logging, though HA runs on IPv4, and the whole network around it also uses IPv4.
## Environment

- Add-on with the issue: Samba share
- Add-on release with the issue: 9.3.0
- Last working add-on release (if known): previous add-on and HA and OS versions had the same problem, I'm using HA only in the last 2 months
- Operating environment (OS/Supervised): HASS OS 5.10 (Supervisor 2020.12.7, HA 2021.1.1)

## Problem-relevant configuration

Samba config:
```yaml
workgroup: WORKGROUP
username: ****
password: ****
interface: localhost
allow_hosts:
  - localhost
veto_files:
  - ._*
  - .DS_Store
  - Thumbs.db
  - icon?
  - .Trashes
compatibility_mode: false
```
Yes, only localhost, because I access HA through SSH, tunneling ports 139 and 445.

## Traceback/Error logs

```txt

```

**Comment by lmagyar** [comment]
Solution: RTFM, ie. do not use `interface: localhost` leave it empty as suggested in the documentation: `interface: ''` works without repeating log entries.

**Comment by lmagyar** [comment]
### Background on this issue

Samba needs a non-loopback, non-ipv6, local interface to listen on and become browser on it. Without it, it works, but reloads the interfaces in an infinite loop forever to check, whether a non-loopback, non-ipv6, local interface is added. This reload causes the error message that this issue is about.

https://github.com/samba-team/samba/blob/master/source3/nmbd/nmbd.c#L370
```c
		/* We only count IPv4, non-loopback interfaces here. */
		while (iface_count_v4_nl() == 0) {
			usleep(NMBD_WAIT_INTERFACES_TIME_USEC);
			load_interfaces();
		}
```

### General solutions

- If you want to run Samba on a "real" network: maybe something is misconfigured, or the selected interface is not yet up (user needs to log in, wifi, etc.)

- If you don't want to run Samba on a "real" network _(in my case I wanted Samba to be accessible only from within the host, because the host will be accessed through SSH, and ports 139 and 445 are forwarded through SSH, resulting a direct SSH tunnel protected access from SSH client PC to Samba add-on)_: next to `lo` loopback, give it a non-loopback, non-ipv6, local interface, I used `docker0`, now Samba is a master browser on it's mini-network and happy with it, no more repeating log messages. Example:
```yaml
allow_hosts:
  - localhost
interface: lo, docker0
```
