### ISSUE TITLE
DuckDNS & Nginx SSL proxy not working

### ISSUE THREAD

**Issue by HexRebuilt** [home-assistant/addons#1764]
## The problem

Hi everyone, I cannot access home assistant outside the network with  the addons duckDNS and NGINX Home Assistant SSL proxy. I've also forwared the ports 80 and 443 to the same ones on the homeassistant as indicated by the documentation.
Both the addons seems to be running from the Logs but the only way that i can access the web interface is by using the local address https://192.168.0.107:8123. And i get this error with the certificate "_SSL_ERROR_BAD_CERT_DOMAIN_" because it is valid only for the duckdns address. Also if i open the informations about the certificates the duckdns address is correct.

## Environment

- Add-on with the issue: NGINX Home Assistant SSL proxy
- Add-on release with the issue: 3.0.1
- Last working add-on release (if known): 
- Operating environment (OS/Supervised):  Home Assistant OS 2021.1.2 (running on ProxmOS)

## Problem-relevant configuration

**Modem port-forwarding**
![immagine](https://user-images.githubusercontent.com/32871843/104719239-74854280-572c-11eb-9ae3-14555edf02ad.png)
I know that it is in Italian but it's just the _service name, external port, forwarded internal port, internal ip address_.

**DuckDNS configuration:**
```lets_encrypt:
  accept_terms: true
  certfile: fullchain.pem
  keyfile: privkey.pem
token: XXX
domains:
  - XXX.duckdns.org
aliases: []
seconds: 300
```

**Nginx Home Assistant SSL proxy configuration**
```
domain: XXX.duckdns.org
certfile: fullchain.pem
keyfile: privkey.pem
hsts: max-age=31536000; includeSubDomains
cloudflare: false
customize:
  active: false
  default: nginx_proxy_default*.conf
  servers: nginx_proxy/*.conf
```
Also i've set the container ports to be forwarded to the same host ports 443:433 80:80

**config.yaml**
```yaml
default_config:

homeassistant:
  internal_url: "http://192.168.0.107"
  external_url: !secret https_address

http:
  #server_port: 8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: True
  login_attempts_threshold: 3
```
If I comment the ssl_certificate and key I'm not able to access the web interface.

## Traceback/Error logs

**DuckDNS log:**
```[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
# INFO: Using main config file /data/workdir/config
+ Account already registered!
[10:55:31] INFO: OK
x.x.x.x
NOCHANGE
# INFO: Using main config file /data/workdir/config
Processing xxx.duckdns.org
 + Checking domain name(s) of existing cert... unchanged.
 + Checking expire date of existing cert...
 + Valid till Apr 15 09:31:26 2021 GMT Certificate will not expire
(Longer than 30 days). Skipping renew!
[11:00:36] INFO: OK
x.x.x.x
NOCHANGE
```

**Nginx:**
```[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[10:56:02] INFO: Running nginx...
```

## Additional information
i've also tried to use the Nginx Proxy Manager but after configuring it the proxy was always offline.

Thanks to everyone in advance

**Comment by IvanNik** [comment]
I have the same issue, please advise

**Comment by HexRebuilt** [comment]
yeah for the entire world works, but i'm sure that i'm doing something wrong because it doesn't for me

**Comment by bangan1910** [comment]
I'm still very new to this, (in fact, my first post), so don't hit me too hard if i say something stupid, but did you forward port 8123?

**Comment by HexRebuilt** [comment]
yes i did and also it's not needed with NGINX

**Comment by FSund** [comment]
I'm having very similar issues as you, and have the exact same setup.

Are you able to access via http? `http://192.168.0.107:8123`

**Comment by FSund** [comment]
The [NGINX docs](https://github.com/home-assistant/addons/blob/master/nginx_proxy/DOCS.md) says to remove `ssl_certificate` and `ssl_key` from the `http` section in `configuration.yaml`, but I'm not sure how this affects things.

**Comment by FSund** [comment]
I got my setup working.

DuckDNS config
```
lets_encrypt:
  accept_terms: true
  certfile: fullchain.pem
  keyfile: privkey.pem
token: <token>
domains:
  - <home>.duckdns.org
aliases: []
seconds: 300
```

NGINX config
```
domain: <home>.duckdns.org
certfile: fullchain.pem
keyfile: privkey.pem
hsts: max-age=31536000; includeSubDomains
cloudflare: false
customize:
  active: false
  default: nginx_proxy_default*.conf
  servers: nginx_proxy/*.conf
```

Relevant `configuration.yaml` parts
```
http:
  # not needed after installing NGINX
  # (adding ssl_cert and key will force the use of https!)
  #ssl_certificate: /ssl/fullchain.pem
  #ssl_key: /ssl/privkey.pem

homeassistant:
  external_url: https://<home>.duckdns.com:8123
  internal_url: http://192.168.1.<local>:8123
```
Not sure `external_url` and `internal_url` are required, but I don't dare touch the setup at this point.

I've forwarded 443 TCP to my local IP
![image](https://user-images.githubusercontent.com/3352483/106192862-0705f700-61ad-11eb-996a-ce878714b72e.png)

Access via `http://192.168.1.<local>:8123` locally works and via `https://<home>duckdns.com` externally.

Hope this can be of help to anyone.
