### ISSUE TITLE
MQTT User?

### ISSUE THREAD

**Issue by jwilleke** [home-assistant/addons#1765]
## The problem
What to do with MQTT User?

Documentation Page says:
_Create a new user for MQTT via the Configuration -> Users (manage users). Notes:

This name cannot be homeassistant or addon, those are reserved usernames.
If you do not see the option to create a new user, ensure that Advanced Mode is enabled in your profile._

But I fail to see what is to be done with this created user?

## Environment

- Add-on with the issue: MQTT
- Add-on release with the issue:  Current version: 5.1
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): Home Assistant OS 5.10/core-2021.1.3/supervisor-2021.01.4

## Problem-relevant configuration

```yaml
logins: []
anonymous: false
customize:
  active: false
  folder: mosquitto
certfile: fullchain.pem
keyfile: privkey.pem
require_certificate: false

homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.68.0/24
        - fd00::/8
        - 127.0.0.1
    - type: homeassistant

```

## Traceback/Error logs

```txt
1610790452: Socket error on client <unknown>, disconnecting.
1610790467: New connection from 172.30.32.1 on port 1883.
1610790467: Socket error on client <unknown>, disconnecting.
```
