### ISSUE TITLE
HomeMatic CCU - Homematic Devices need to be resettet after reboot of CCU

### ISSUE THREAD

**Issue by DunklerPhoenix** [home-assistant/addons#1783]
## The problem
All my HomeMatic devices (not the gateway) need to be resetted after a restart of CCU otherwise the devices can't connect to CCU. 
There is no re-learning needed because after the reset of the devices they connect themself again.

## Environment
Used devices: 
2x HmIP-SRH
1x HMIP-SWDO
Gateway: HmIP-RFUSB

- Add-on with the issue: HomeMatic CCU
- Add-on release with the issue: <=11.0.6 
- Last working add-on release (if known): -
- Operating environment (OS/Supervised): Hassio 5.10 | core-2021.1.5 | supervisor-2021.01.7 | HA Blue

## Problem-relevant configuration

```yaml
rf_enable: false
wired_enable: false
hmip_enable: true
rf:
  - type: CCU2
    device: >-
      /dev/serial/by-id/usb-Silicon_Labs_eQ-3_HmIP-RFUSB_3014F738C3-if00-port0
wired:
  - serial: xy
    key: abc
    ip: 192.168.0.0
hmip:
  - type: HMIP_CCU2
    device: /dev/ttyUSB0
regahss_reset: false

```
