### ISSUE TITLE
HomeMatic CCU - Some functions don't work other crash the webinterface

### ISSUE THREAD

**Issue by DunklerPhoenix** [home-assistant/addons#1784]
## The problem
Go to Settings -> Control panel

1. problem: 
CCU Maintenance => crash of webinterface 
May be caused by:
```
Uncaught TypeError: Cannot read property 'firmware' of null
    at webui.js?_version_=2.0pre1:19747
    at webui.js?_version_=2.0pre1:23584
    at XMLHttpRequest.xhr.onreadystatechange (webui.js?_version_=2.0pre1:6402)`
```

2. problem: Security -> Create Backup:
`An internal error was detected in the service software. The diagnostics are being emailed to the service system administrator (root).`

3. problem: time-/position settings => crash webinterface

4. problem: additional software => Upload don't work

5. problem: Update Accesspoints with => crash webinterface

6. problem: Network Settings => crash webinterface

## Environment
Used devices: 
2x HmIP-SRH
1x HMIP-SWDO
Gateway: HmIP-RFUSB

- Add-on with the issue: HomeMatic CCU
- Add-on release with the issue: <=11.0.6 
- Last working add-on release (if known): -
- Operating environment (OS/Supervised): Hassio 5.10 | core-2021.1.5 | supervisor-2021.01.7 | HA Blue

## Problem-relevant configuration

```yaml
rf_enable: false
wired_enable: false
hmip_enable: true
rf:
  - type: CCU2
    device: >-
      /dev/serial/by-id/usb-Silicon_Labs_eQ-3_HmIP-RFUSB_3014F738C3-if00-port0
wired:
  - serial: xy
    key: abc
    ip: 192.168.0.0
hmip:
  - type: HMIP_CCU2
    device: /dev/ttyUSB0
regahss_reset: false

```

## Logs
there are some errors in log, but I don't know how to download the complete log out of supervisor
