### ISSUE TITLE
File Editor: unknown tag !<!input> when editing blueprint

### ISSUE THREAD

**Issue by Bascht74** [home-assistant/addons#1788]
## The problem
I want to edit blueprints and check if the blueprint is valid. 
There is always the "unknown tag":

```
unknown tag !<!input> at line 300, column 38:
     ... ne_ambient: !input scene_ambient
                                         ^
```

## Environment
- Add-on with the issue: File Editor
- Add-on release with the issue: 5.2.0
- Last working add-on release (if known):  not known
- Operating environment (OS/Supervised):  core-2021.1.5, Home Assistant OS 5.10

## Problem-relevant configuration

```yaml
blueprint:
  name: Zone Notification
  description: Send a notification to a device when a person leaves a specific zone.
  domain: automation
  source_url: https://github.com/home-assistant/core/blob/dev/homeassistant/components/automation/blueprints/notify_leaving_zone.yaml
  input:
    person_entity:
      name: Person
      selector:
        entity:
          domain: person
    zone_entity:
      name: Zone
      selector:
        entity:
          domain: zone
    notify_device:
      name: Device to notify
      description: Device needs to run the official Home Assistant app to receive notifications.
      selector:
        device:
          integration: mobile_app

trigger:
  platform: state
  entity_id: !input person_entity

variables:
  zone_entity: !input zone_entity
  # This is the state of the person when it's in this zone.
  zone_state: "{{ states[zone_entity].name }}"
  person_entity: !input person_entity
  person_name: "{{ states[person_entity].name }}"

condition:
  condition: template
  value_template: "{{ trigger.from_state.state == zone_state and trigger.to_state.state != zone_state }}"

action:
  domain: mobile_app
  type: notify
```

## Traceback/Error logs

```txt
unknown tag !<!input> at line 26, column 34:
      entity_id: !input person_entity
                                     ^
```

## Additional information
Can you guys add the "!input" tag, so that the complete YAML code of a blueprint can be checked?
