### ISSUE TITLE
Addon homematic does not start with default config

### ISSUE THREAD

**Issue by p3dda** [home-assistant/addons#1828]
## The problem

After update to version 11.1.0, the addon does not start with the previously working config or the default config from documentation. As in the default config, I have set _hmip_enable_ to false, and it refuses to start because the _/dev/ttyUSB0_ device is missing. This should not be relevant since hmip is disabled.

## Environment

- Add-on with the issue: homematic
- Add-on release with the issue: 11.1.0
- Last working add-on release (if known):  11.0.6
- Operating environment (OS/Supervised):  supervisor-2021.02.6

## Problem-relevant configuration

```yaml
rf_enable: true
wired_enable: false
hmip_enable: false
rf:
  - type: CCU2
    device: /dev/ttyAMA0
wired:
  - serial: xy
    key: abc
    ip: 192.168.0.0
hmip:
  - type: HMIP_CCU2
    device: /dev/ttyUSB0
regahss_reset: false
```

## Traceback/Error logs

```txt
21-02-09 08:29:56 ERROR (MainThread) [supervisor.addons.addon] Add-on core_homematic has invalid options: Device /dev/ttyUSB0 does not exists!. Got {'rf_enable': True, 'wired_enable': False, 'hmip_enable': False, 'rf': [{'type': 'CCU2', 'device': '/dev/ttyAMA0'}], 'wired': [{'serial': 'xy', 'key': 'abc', 'ip': '192.168.0.0'}], 'hmip': [{'type': 'HMIP_CCU2', 'device': '/dev/ttyUSB0'}], 'regahss_reset': False}
21-02-09 08:29:56 WARNING (MainThread) [supervisor.addons] Can't start Add-on core_homematic
```

## Additional information
Setting the hmip device to some existing device like /dev/ttyS0 allows the plugin to start.
It seems the config validation requires the given devices no matter if the communication type in enabled or not.
