### ISSUE TITLE
DHCP server V1.2 ethernet interface issue

### ISSUE THREAD

**Issue by mattlward** [home-assistant/addons#1842]
## The problem

DHCP Server fails to start with the following loged complaint"

Multiple interfaces match the same shared network: eno eno1
Failed to get interface index: No such device

## Environment

- Add-on with the issue:
- Dhcp Server
- Add-on release with the issue: 
- V1.2
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): 
```
System Health

version: core-2021.2.2
installation_type: Home Assistant Supervised
dev: false
hassio: true
docker: true
virtualenv: false
python_version: 3.8.7
os_name: Linux
os_version: 4.19.0-13-amd64
arch: x86_64
timezone: America/Chicago


GitHub API: ok
Github API Calls Remaining: 4926
Installed Version: 1.11.2
Stage: running
Available Repositories: 743
Installed Repositories: 11


host_os: Debian GNU/Linux 10 (buster)
update_channel: stable
supervisor_version: supervisor-2021.02.6
docker_version: 20.10.2
disk_total: 218.1 GB
disk_used: 9.9 GB
healthy: true
supported: true
supervisor_api: ok
version_api: ok
installed_addons: Backup Hassio to Google Drive (1.7.2), Dropbox Sync (1.3.0), Duck DNS (1.12.5), FTP (4.0.0), File editor (5.2.0), Log Viewer (0.9.1), RPC Shutdown (2.2), WireGuard (0.5.0), Mosquitto broker (5.1), SSH & Web Terminal (8.0.1), Samba share (9.3.0), TasmoAdmin (0.14.0), motionEye (0.11.0), AdGuard Home (3.0.0), Portainer (1.4.0), Glances (0.11.0), Check Home Assistant configuration (3.6.0), Network UPS Tools (0.5.0), DHCP server (1.2)


dashboards: 1
resources: 3
views: 16
mode: storage
```
Only 1 ethernet interface and wlan is disabled in bios.

## Problem-relevant configuration

```yaml
default_lease: 86400
max_lease: 172800
domain: home.local
dns:
  - 192.168.1.1
  - 8.8.4.4
networks:
  - subnet: 192.168.1.0
    netmask: 255.255.255.0
    range_start: 192.168.1.165
    range_end: 192.168.1.225
    broadcast: 192.168.1.255
    gateway: 192.168.1.1
    interface: eth0
hosts:
  - name: yeelight
    mac: '28:6C:07:B1:43:1C'
    ip: 192.168.1.172

```

## Traceback/Error logs

```txt
[16:38:01] INFO: Creating DHCP configuration...
[16:38:04] INFO: Starting DHCP server...
Internet Systems Consortium DHCP Server 4.4.1
Copyright 2004-2018 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/
Config file: /etc/dhcpd.conf
Database file: /data/dhcpd.lease
PID file: /var/run/dhcp/dhcpd.pid
Wrote 0 deleted host decls to leases file.
Wrote 0 new dynamic host decls to leases file.
Wrote 0 leases to leases file.
Multiple interfaces match the same shared network: eth0 eno1
Failed to get interface index: No such device
If you think you have received this message due to a bug rather
than a configuration issue please read the section on submitting
bugs on either our web page at www.isc.org or in the README file
before submitting a bug.  These pages explain the proper
process and the information we find helpful for debugging.
exiting.
```

## Additional information
I was hoping to set this up as a backup to my dhcp server, an old router in access point mode running on DD-WRT.
Sort of a warm backup.
