### ISSUE TITLE
dnsmasq 1.4 fails to start

### ISSUE THREAD

**Issue by ocalvo** [home-assistant/addons#1850]
## The problem
Add-on fails to start with error:
```
[FATAL tini (6)] exec /init failed: Permission denied
```

## Environment

- Add-on with the issue: dnsmaq
- Add-on release with the issue: 1.4
- Last working add-on release (if known): 1.3
- Operating environment (OS/Supervised): hassos

## Problem-relevant configuration

```yaml
defaults:
  - 192.168.1.1
forwards: []
hosts:
  - host: dc.mydomain.io
    ip: 192.168.1.2
services: []
```

## Traceback/Error logs

```txt
[FATAL tini (6)] exec /init failed: Permission denied
```
