### ISSUE TITLE
Homematic Add-On not working anymore after update to 11.1.2

### ISSUE THREAD

**Issue by kegelmeier** [home-assistant/addons#1874]
## The problem

The add-on was running perfectly fine until I installed update 11.1.2. However, I do not see any errors. The CCU launches and I can access the Web UI. However, no devices can connect and send or retrieve data.

## Environment

- Add-on with the issue: Homematic
- Add-on release with the issue: 11.1.2
- Last working add-on release (if known): 11.1.1
- Operating environment (OS/Supervised): supervisor-2021.02.9

## Problem-relevant configuration

```
rf_enable: false
wired_enable: false
hmip_enable: true
rf:
  - type: CCU2
    device: /dev/ttyAMA0
wired:
  - serial: xy
    key: abc
    ip: 192.168.0.0
hmip:
  - type: HMIP_CCU2
    device: /dev/ttyUSB0
regahss_reset: false

```
## Additional information

I am only using HMIP with the HmIP-RFUSB
