### ISSUE TITLE
deCONZ broken - Cannot connect to Conbee 2 stick

### ISSUE THREAD

**Issue by Nutti85** [home-assistant/addons#1881]
## The problem

My Conbee 2 stick is suddenly unreachable by Home Assistant. Under the webui -> Gateway -> Firmware it says disconnected

## Environment

Running on a Windows PC in Virtualbox

- Add-on with the issue:
deCONZ
- Add-on release with the issue: 
 6.7.2
- Last working add-on release (if known): 
6.7.0
- Operating environment (OS/Supervised): 
Home Assistant OS 5.12
core-2021.2.3
supervisor-2021.02.11
## Problem-relevant configuration

```yaml
device: /dev/serial/by-id/usb-0658_0200-if00
```
Also tried
```yaml
device: /dev/ttyACM0
```
## Traceback/Error logs

```
[10:18:50] INFO: Starting the deCONZ gateway...
QCoreApplication::arguments: Please instantiate the QApplication object first
libpng warning: iCCP: known incorrect sRGB profile
10:17:28:701 GW sd-card image version file does not exist: /data/.local/share/dresden-elektronik/deCONZ/gw-version
10:21:26:070 COM: /dev/ttyACM0 : 0200 (0x0658/0x0200)
10:21:26:071 COM: /dev/serial/by-id/usb-0658_0200-if00 / serialno: , ConBee II
10:21:26:073 auto connect com /dev/serial/by-id/usb-0658_0200-if00
10:21:26:074 enqueue event config/localtime for /config/
10:21:26:087 Serial com disconnected, reason: 4
10:21:26:090 device disconnected reason: 4, index: 0
```

## Additional information
Stick is found by both VirtualBox and the Supervisor.

Seems similar to this issue: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3170

**Comment by fribse** [comment]
I saw this as well, after reconfiging it in add-ons and then restart it, then it was found again.
Had to do this for the z-wave as well.
I now see two zigbee devices in the machine:
```
  - name: 3-1
    sysfs: '/sys/devices/pci0000:00/0000:00:1d.0/usb3/3-1'
    dev_path: /dev/bus/usb/003/019
    subsystem: usb
    by_id: null
    attributes:
      BUSNUM: '003'
      DEVNAME: /dev/bus/usb/003/019
      DEVNUM: 019
      DEVPATH: '/devices/pci0000:00/0000:00:1d.0/usb3/3-1'
      DEVTYPE: usb_device
      DRIVER: usb
      ID_BUS: usb
      ID_MODEL: ConBee_II
      ID_MODEL_ENC: ConBee\x20II
      ID_MODEL_ID: '0030'
      ID_PATH: 'pci-0000:00:1d.0-usb-0:1'
      ID_PATH_TAG: pci-0000_00_1d_0-usb-0_1
      ID_REVISION: '0100'
      ID_SERIAL: dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2139528
      ID_SERIAL_SHORT: DE2139528
      ID_USB_INTERFACES: ':020201:0a0000:'
      ID_VENDOR: dresden_elektronik_ingenieurtechnik_GmbH
      ID_VENDOR_ENC: dresden\x20elektronik\x20ingenieurtechnik\x20GmbH
      ID_VENDOR_ID: 1cf1
      MAJOR: '189'
      MINOR: '274'
      PRODUCT: 1cf1/30/100
      SUBSYSTEM: usb
      TYPE: 2/0/0
      USEC_INITIALIZED: '1370610511'
  - name: ttyACM2
    sysfs: '/sys/devices/pci0000:00/0000:00:1d.0/usb3/3-1/3-1:1.0/tty/ttyACM2'
    dev_path: /dev/ttyACM2
    subsystem: tty
    by_id: >-
      /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2139528-if00
    attributes:
      DEVLINKS: >-
        /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2139528-if00
        /dev/serial/by-path/pci-0000:00:1d.0-usb-0:1:1.0
      DEVNAME: /dev/ttyACM2
      DEVPATH: '/devices/pci0000:00/0000:00:1d.0/usb3/3-1/3-1:1.0/tty/ttyACM2'
      ID_BUS: usb
      ID_MODEL: ConBee_II
      ID_MODEL_ENC: ConBee\x20II
      ID_MODEL_ID: '0030'
      ID_PATH: 'pci-0000:00:1d.0-usb-0:1:1.0'
      ID_PATH_TAG: pci-0000_00_1d_0-usb-0_1_1_0
      ID_REVISION: '0100'
      ID_SERIAL: dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2139528
      ID_SERIAL_SHORT: DE2139528
      ID_TYPE: generic
      ID_USB_DRIVER: cdc_acm
      ID_USB_INTERFACES: ':020201:0a0000:'
      ID_USB_INTERFACE_NUM: '00'
      ID_VENDOR: dresden_elektronik_ingenieurtechnik_GmbH
      ID_VENDOR_ENC: dresden\x20elektronik\x20ingenieurtechnik\x20GmbH
      ID_VENDOR_ID: 1cf1
      MAJOR: '166'
      MINOR: '2'
      SUBSYSTEM: tty
      TAGS: ':systemd:'
      USEC_INITIALIZED: '1370615199'

```
