### ISSUE TITLE
Preset Modes for climate entities not displayed properly

### ISSUE THREAD

**Issue by Se7enair** [home-assistant/addons#1912]
## The problem

The preset_mode is not displayed in the attributes. The entity changes it, but it still shows "none".
As you can see on the picture, the valve is completely open, but the preset_mode attribute on the climate still shows "none"
![grafik](https://user-images.githubusercontent.com/1680106/110590715-7097fe80-8178-11eb-801c-c411c777da3f.png)

## Environment

- Add-on with the issue: Z-Wave JS
- Add-on release with the issue:  0.1.10
- Last working add-on release (if known): dont know if it ever worked
- Operating environment (OS/Supervised): core-2021.3.2, supervisor-2021.03.4, Home Assistant OS 5.12

## Problem-relevant configuration

```yaml
service: climate.set_preset_mode
data:
  preset_mode: Full power
target:
  entity_id: climate.bad_heizung
```

## Traceback/Error logs

```txt

```
