### ISSUE TITLE
Birth and Last Will messages not dispatched

### ISSUE THREAD

**Issue by catmembert** [home-assistant/addons#1913]
## The problem

birth_message and will_message events are not dispatched nor retained when HA starts or shuts down.

## Environment

- Add-on with the issue: Mosquitto broker
- Add-on release with the issue: 5.1.1
- Last working add-on release (if known): n/a
- Operating environment (OS/Supervised): OS

## Problem-relevant configuration

```yaml
mqtt:
  broker: 'core_mosquitto'
  username: 'my_mqtt_user'
  password: 'my_mqtt_password'
  discovery_prefix: 'ha'
  discovery: true
  birth_message:
    topic: 'ha/status'
    payload: 'online'
    retain: true
  will_message:
    topic: 'ha/status'
    payload: 'offline'
    retain: true
```

## Traceback/Error logs

```txt
nothing relevant
```

## Additional information
I stumble upon this one while trying using a lib for custom MQTT devices. First I reported the issue to the lib author, see here for details : https://github.com/plapointe6/CustomHADevicesCollection/issues/1
Then using MQTTfx I tried to subscribe to ha/status but nothing seems to be dispatched when HA is shut down or restarted.
