### ISSUE TITLE
SSH & Web Terminal:  after few days of working cannot be called from Home Assistant any more (unitl restart)

### ISSUE THREAD

**Issue by tpudel82** [home-assistant/addons#1945]
## The problem

I'm using SSH & Web Terminal and script which uses catt to cast my lovelace to a google device (Lenovo Smart Display).
This works flawlessly for a few days, until it doesn't anymore, without any specific reason.
When it stops working the script itself works perfectly when called from within the terminal. But it doesn't work when called by Home Assistant anymore.
When I restart the SSH & Web Terminal Plugin everything works normally again. So I'm guessing something is wrong with the add-on. 
Can you help me to resolve the problem - or maybe there is some workaround?

## Environment

- Add-on with the issue: SSH & Web Terminal
- Add-on release with the issue: 8.1.0
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): HAAS supervised on UBuntu: 18.04 LS

## Problem-relevant configuration

Here is my configuration of the addon:
```
ssh:
  username: tpudel
  password: ******
  authorized_keys: []
  sftp: false
  compatibility_mode: false
  allow_agent_forwarding: false
  allow_remote_port_forwarding: false
  allow_tcp_forwarding: false
zsh: true
share_sessions: false
packages: []
init_commands:
  - python3 -m pip install catt
```

here is the script:
```
if ! catt -d "Kuchnia" status | grep 'PLAYING'; then 
    catt -d "Kuchnia" volume 0
    catt -d "Kuchnia" cast_site http://192.168.0.200:8123/tablet-dashboards/dashboard?kiosk
fi
```

and here is the automation:
```
- id: "cast_to_dashboard"
  alias: Cast To Dashboard
  description: ""
  trigger:
    - minutes: /9
      platform: time_pattern
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: media_player.lenovo_smart_display
        state: "off"
      - condition: state
        entity_id: media_player.lenovo_smart_display
        state: "idle"
  action:
    - data:
        addon: a0d7b954_ssh
        input: bash /config/cast.sh
      service: hassio.addon_stdin
```

## Traceback/Error logs

```txt

```
