### ISSUE TITLE
Invalid YAML for !secret username / password in "SSH & Web Terminal" config

### ISSUE THREAD

**Issue by Coolie1101** [home-assistant/addons#1996]
## The problem

Unable to use/configure !secret username or !secret password.

## Environment

- Add-on with the issue: SSH & Web Terminal
- Add-on release with the issue: Current version: 8.2.1
- Last working add-on release (if known): Unknown
- Operating environment (OS/Supervised): Home Assistant OS 5.13 / supervisor-2021.04.3

## Problem-relevant configuration

```yaml
ssh:
  username: !secret username
  password: !secret password
  authorized_keys: []
  sftp: false
  compatibility_mode: false
  allow_agent_forwarding: false
  allow_remote_port_forwarding: false
  allow_tcp_forwarding: false
zsh: true
share_sessions: false
packages: []
init_commands: []

```

## Traceback/Error logs

```txt
NONE
```

## Additional information
![image](https://user-images.githubusercontent.com/28989417/116930704-15413480-ac2e-11eb-80ae-04288a7510ff.png)
