### ISSUE TITLE
Bridge configuration no longer working with Mosquitto add-on v6.0.0

### ISSUE THREAD

**Issue by theOzzieRat** [home-assistant/addons#2011]
## The problem
After updating the Mosquitto add-on to version 6.0.0 my bridge configuration is no longer being loaded.

## Environment
Mosquitto add-on v6.0.0

- Add-on with the issue: Mosquitto
- Add-on release with the issue:  6.0.0
- Last working add-on release (if known):  5.1.1
- Operating environment (OS/Supervised):  haasos 2021.5.4

## Problem-relevant configuration

```yaml
logins:
  - username: mqtt-server
    password: some-random-password
anonymous: false
customize:
  active: true
  folder: mosquitto
```
in /share/mosquitto is a file called bridge.conf with a valid bridge config.

With 5.1.1 and earlier the log shows 

```
[19:29:43] INFO: Initialize Home Assistant discovery
[19:29:43] INFO: Start Mosquitto daemon
1621416583: Loading config file /share/mosquitto/bridge.conf
1621416583: mosquitto version 1.6.3 starting
```

in 6.0.0 this is missing

## Traceback/Error logs

```txt

```
