### ISSUE TITLE
Username with colon is NG in Mosquitto broker 6.0.0

### ISSUE THREAD

**Issue by nao-pon** [home-assistant/addons#2014]
## The problem

I'm using a locally configured Meross device. Meross devices use a MAC address with a colon in the username.

Until 5.1.1, a username with a colon was allowed, but from 6.0.0 it became unavailable and the Meross device became unusable.

## Environment

- Add-on with the issue: Mosquitto broker
- Add-on release with the issue: 6.0.0
- Last working add-on release (if known): 5.1.1
- Operating environment (OS/Supervised): supervisor-2021.04.3

## Problem-relevant configuration

```yaml
logins:
  - username: '48:e1:e9:xx:xx:xx'
    password: meross_eb61de8166d394ecba0bc84cab7axxxx
anonymous: false
customize:
  active: false
  folder: mosquitto
certfile: fullchain.pem
keyfile: privkey.pem
require_certificate: false
```

## Traceback/Error logs

```txt

```

## Additional information
The username is fixed in the device firmware and cannot be changed by us.
