### ISSUE TITLE
mqtt addon doesn't allow configuring logins with passwords from secrets.yaml

### ISSUE THREAD

**Issue by pbzdyl** [home-assistant/addons#2015]
## The problem

I cannot configure MQTT addon logins with passwords fetched from HA's secrets.yaml file

## Environment

- Add-on with the issue: MQTT
- Add-on release with the issue: 6.0.1
- Last working add-on release (if known): ---
- Operating environment (OS/Supervised): Home Assistant OS 5.13

## Problem-relevant configuration

```yaml
logins:
  - username: mqtt
    password: !secret mqtt_password
customize:
  active: false
  folder: mosquitto
certfile: fullchain.pem
keyfile: privkey.pem
require_certificate: false
anonymous: false
```

## Traceback/Error logs

The config editor in the Add-on GUI in Supervisor shows 'Invalid YAML' message and doesn't allow saving the config.

## Additional information

N/A
