### ISSUE TITLE
MQTT log extremely delayed  updating after initial startup sequence 

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/addons#2026]
## The problem

After the initial startup, MQTT log <strike>doesn't</strike> updates extremely delayed. 

Connections of subscribing clients are registered alright, as can be seen in mqtt-explorer (which is blazing fast btw, a huuuge improvement compared to 5.1)

## Environment

- Add-on with the issue: Mosquitto broker
- Add-on release with the issue: 6.0.1
- Last working add-on release (if known): 5.1
- Operating environment (OS/Supervised): OS

## Problem-relevant configuration

```yaml
logins:
  - username: redacted
    password: redacted
customize:
  active: false
  folder: mosquitto
certfile: fullchain.pem
keyfile: privkey.pem
require_certificate: false
```

## Traceback/Error logs

nothing happening after the initial
```txt
1621592194: Warning: Mosquitto should not be run as root/administrator.
1621592194: mosquitto version 1.6.12 running
1621592194: New connection from 127.0.0.1 on port 1883.
1621592194: Socket error on client <unknown>, disconnecting.
1621592194: New connection from 192.168.1.27 on port 1883.
1621592194: New client connected from 192.168.1.27 as 70:B3:D5:6F:31:F2 (p1, c0, k60, u'redacted').
```

only after coming back to the add-on for quite some time, the log finally updated, and, that is odd, the timestamps seem not to indicate this.Maybe it is a frontend issue while the backend does work properly. That would at least explain the immediate streams in Mqtt explorer.
