### ISSUE TITLE
Unknown clients connect to MQTT

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/addons#2028]
## The problem

in the MQTT log several unknown (to me), but identified clients connect, and get disconnected. Is this a bug/danger?

## Environment

- Add-on with the issue: Mosquitto broker
- Add-on release with the issue:  6.0.1
- Last working add-on release (if known): 5.1
- Operating environment (OS/Supervised): OS

## Problem-relevant configuration

```yaml
logins:
  - username: redacted
    password: redacted
customize:
  active: false
  folder: mosquitto
certfile: fullchain.pem
keyfile: privkey.pem
require_certificate: false
```

## Traceback/Error logs

```txt
1621613733: New connection from 162.142.125.40 on port 8883.
1621613733: New client connected from 162.142.125.40 as CENSYS (p2, c0, k10).
1621613748: Socket error on client CENSYS, disconnecting.
1621613901: Saving in-memory database to /data/mosquitto.db.
1621614943: New connection from 216.218.206.67 on port 8883.
1621614944: New client connected from 216.218.206.67 as MqttClient (p2, c1, k60).
1621614944: Socket error on client MqttClient, disconnecting.
```

## Additional information

Can't relate these to any configured action in the clients that are setup to subscribe to the broker. Neither the ip addresses nor the names CENSYS and MqttClient are known clients in my configuration. Whats even more significant is they apparently dont use a Username to login?
