### ISSUE TITLE
Add-on core_duckdns can't write options

### ISSUE THREAD

**Issue by franc3sc0** [home-assistant/addons#2051]
## The problem

I’ve recently installed HA OS 5.13 on a Raspberry Pi 3b following [these instructions](https://www.home-assistant.io/installation/raspberrypi#install-home-assistant-operating-system). I’ve installed core add-ons _File editor_ and _Samba share_ through the Add-on Store UI and both work fine.

I’ve then installed the _Duck DNS_ core add-on, modified its Configuration (see below) and saved it.
When trying to start the Duck DNS add-on, I get a pop-up with the following error message:

> ## Failed to start add-on. 
> Unknown error, see supervisor

Detailed errors from the Hassio supervisor log are further below.

## Environment

- Add-on with the issue: Duck DNS
- Add-on release with the issue: 1.12.5
- Last working add-on release (if known): -
- Operating environment (OS/Supervised): OS
- Home Assistant OS 5.13
- Core version: core-2021.5.5
- Supervisor version: supervisor-2021.04.3

## Problem-relevant configuration

```yaml
lets_encrypt:
  accept_terms: true
  certfile: fullchain.pem
  keyfile: privkey.pem
token: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
domains:
  - xxxxxx.duckdns.org
aliases: []
seconds: 300
```

## Traceback/Error logs

```txt
21-05-29 20:33:58 ERROR (MainThread) [supervisor.utils.json] Can't write /data/addons/data/core_duckdns/options.json: [Errno 2] No such file or directory: '/data/addons/data/core_duckdns/tmpg38xdz0b'
21-05-29 20:33:58 ERROR (MainThread) [supervisor.addons.addon] Add-on core_duckdns can't write options
```
