### ISSUE TITLE
MQTT Not working after new installation of HASSIO

### ISSUE THREAD

**Issue by cekko877** [home-assistant/addons#2053]
i am not able to publish and subscribe data after the new installation of HASSIO into Raspberry pi4.
I tried
Reinstall MQTT broker Addon
Delete MQTT intergration and re-add it (auto discovery)
Delete and recreate the user in Home Assistant that i am using for MQTT

**MQTT Addon config: (default)**

logins: []
anonymous: false
customize:
  active: false
  folder: mosquitto
certfile: fullchain.pem
keyfile: privkey.pem
require_certificate: false

**MQTT Addon log:**

1587126149: Warning: Mosquitto should not be run as root/administrator.
1587126151: New connection from 172.30.32.1 on port 1883.
1587126152: Socket error on client <unknown>, disconnecting.

**Comment by balbulator** [comment]
Try to set username and password in Mosquitto broker setup
```
logins:
  - username: user
    password: password
customize:
  active: false
  folder: mosquitto
certfile: fullchain.pem
keyfile: privkey.pem
require_certificate: false
anonymous: false
```
