### ISSUE TITLE
smbd crashing with email address as Windows username

### ISSUE THREAD

**Issue by andrewwa0** [home-assistant/addons#2055]
## The problem

In Windows 10, navigating to \\homeassistant.local\ crashes smdb when the Windows username is an email address.
On a new Windows 10 build, without a prior samba login, the current username is sent for authentication and crashes smdb before I can be prompted for the configured username and password.

## Environment

- Add-on with the issue: samba share
- Add-on release with the issue: 9.5.0
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): 

## Problem-relevant configuration

```yaml
workgroup: WORKGROUP
username: homeassistant
password: REDACTED
allow_hosts:
  - 192.168.1.107/0
  - 192.168.1.141/0
veto_files:
  - ._*
  - .DS_Store
  - Thumbs.db
  - icon?
  - .Trashes
compatibility_mode: false

```

## Traceback/Error logs

```txt
check_ntlm_password:  Authentication for user [REDACTED@gmail.com] -> [REDACTED@gmail.com] FAILED with error NT_STATUS_NO_SUCH_USER, authoritative=1
===============================================================
INTERNAL ERROR: Signal 11: Segmentation fault in pid 287 (4.13.8)
If you are running a recent Samba version, and if you think this problem is not yet fixed in the latest versions, please consider reporting this bug, see https://wiki.samba.org/index.php/Bug_Reporting
===============================================================
PANIC (pid 287): Signal 11: Segmentation fault in 4.13.8
unable to produce a stack trace on this platform
coredump is handled by helper binary specified at /proc/sys/kernel/core_pattern
Registered MSG_REQ_POOL_USAGE
```
The crashes repeat up to pid 310
