### ISSUE TITLE
Homematic RF on HAOS 6 : Device or resource busy

### ISSUE THREAD

**Issue by Robbilie** [home-assistant/addons#2087]
## The problem
After the home assistant os 6 update and changing the homematic rf tty from AMA0 to S0 i get an error when starting the addon:
/var/run/s6/etc/cont-init.d/hm_rfd.sh: line 20: echo: write error: Device or resource busy

## Environment

core-2021.6.6
supervisor-2021.06.3
Home Assistant OS 6.0
Raspi 4 4GB 64

HomeMatic CCU
Current version: 11.2.2

Worked on the prior OS release.

## Problem-relevant configuration

```yaml
rf_enable: true
wired_enable: false
hmip_enable: true
rf:
  - type: CCU2
    device: /dev/ttyS0
wired:
  - serial: xy
    key: abc
    ip: 192.168.0.0
hmip:
  - type: HMIP_CCU2
    device: /dev/ttyUSB0
regahss_reset: false

```

## Traceback/Error logs

```txt
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] certs.sh: executing... 
[cont-init.d] certs.sh: exited 0.
[cont-init.d] env.sh: executing... 
[cont-init.d] env.sh: exited 0.
[cont-init.d] hm_ip.sh: executing... 
[12:58:26] INFO: Setup HmIP-RF
[cont-init.d] hm_ip.sh: exited 0.
[cont-init.d] hm_rfd.sh: executing... 
[12:58:28] INFO: Setup BidCos-RF
/var/run/s6/etc/cont-init.d/hm_rfd.sh: line 20: echo: write error: Device or resource busy
[cont-init.d] hm_rfd.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] hmip.sh: executing... 
[cont-finish.d] hmip.sh: exited 0.
[cont-finish.d] regahss.sh: executing... 
[cont-finish.d] regahss.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```
