### ISSUE TITLE
Configurator broken on latest dev

### ISSUE THREAD

**Issue by TheZoker** [home-assistant/addons#2095]
## The problem

On the current dev version, the configurator seems broken. I can't select any file (no file is even shown) and the UI seems broken (see screenshot below)

## Environment

- Add-on with the issue: `configurator`
- Add-on release with the issue: `5.3.1`
- Last working add-on release (if known): ?
- Operating environment (OS/Supervised): OS 7.0.dev20210619

## Problem-relevant configuration

```yaml
dirsfirst: true
enforce_basepath: true
git: false
ignore_pattern:
  - __pycache__
  - .cloud
  - .storage
  - deps
ssh_keys: []
```

## Traceback/Error logs

```txt
none
```

## Additional information

Core version: `core-2021.7.0.dev20210628`
SU: `supervisor-2021.06.dev2601`
OS: `7.0.dev20210619`

![Screenshot 2021-06-28 215533](https://user-images.githubusercontent.com/1368405/123697106-ce05a780-d85c-11eb-823c-86099c041fa2.png)
