### ISSUE TITLE
deCONZ 6.9.0: Light effect colorloop stopped working 

### ISSUE THREAD

**Issue by jsa91** [home-assistant/addons#2102]
## The problem

I am using RGB Phillips Hue bulbs with the light effect 'colorloop'. With deCONZ version 6.9.0 this effect has stopped working.
It seems that is not only me who has this problem:
https://community.home-assistant.io/t/effect-colorloop-stopped-working/308065

## Environment

- Add-on with the issue: deCONZ
- Add-on release with the issue: 6.9.0
- Last working add-on release (if known): 
- Operating environment (OS/Supervised):  
Raspberry Pi 3 Model B+
OS Version: Home Assistant OS 6.0
Home Assistant Core: 2021.6.6

## Problem-relevant configuration

```
alias: Hue Loop
sequence:
  - service: light.turn_on
    data:
      entity_id: light.extended_color_light_13
      effect: colorloop
      brightness: 24
      transition: 5
mode: single
icon: mdi:flash-circle

```

## Traceback/Error logs

```txt

```
