### ISSUE TITLE
Nginx: (111: Connection refused) during HA startup

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/addons#2122]
## The problem

during startup, Nginx reports below error, even though the instance is in the list of trusted_proxies. could this be because the address isn't yet available? if so, we should probably be able to 'ignore' this, instead of it issuing an error

## Environment

- Add-on with the issue: Nginx
- Add-on release with the issue: 3.0.2
- Last working add-on release (if known):  Dk
- Operating environment (OS/Supervised): HA OS 2021.7.3

## Problem-relevant configuration

```yaml
  use_x_forwarded_for: true
  trusted_proxies:
#    - 127.0.0.1
    - 172.30.33.7
    - 172.30.32.0/24
#    - 172.30.33.0/24
```

## Traceback/Error logs

```txt
2021/07/19 23:02:51 [error] 222#222: *7441 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.1, server: mydomain.duckdns.org, request: "GET /api/websocket HTTP/1.1", upstream: "http://172.30.32.1:8123/api/websocket", host: "mydomain.duckdns.org:myport"
```

## Additional information
please see: https://community.home-assistant.io/t/nginx-configuration-connection-refused/62407/13?u=mariusthvdb
