### ISSUE TITLE
DuckDNS add-on generates certificates that are incompatible with Android 7.0

### ISSUE THREAD

**Issue by tux2000** [home-assistant/addons#2183]
## The problem

The Let's encrypt SSL certificates that are generated with the current version of the DuckDNS add-on (1.13.0) are not compatible with Android 7.0 which breaks the submission of sensor data to home-assistant from the companion app: https://github.com/home-assistant/android/issues/1709

The dehydrated script has an option to select the algorithm that is used for generating the certificate: 
```
--algo (-a) rsa|prime256v1|secp384r1 Which public key algorithm should be used? Supported: rsa, prime256v1 and secp384r1
```

I changed the the duckDNS add-on locally to use the `prime256v1` algorithm instead of the `secp384r1` (default) which solved the issue on my setup. 

I suggest to expose this command line option through the add-on configuration to facilitate adjustments of the certificate algorithm.

## Environment

- Add-on with the issue: DuckDNS
- Add-on release with the issue: 1.13.0
- Last working add-on release (if known): unknown
- Operating environment (OS/Supervised): Home Assistant Supervised on Debian

## Problem-relevant configuration

```yaml
lets_encrypt:
  accept_terms: true
  certfile: fullchain.pem
  keyfile: privkey.pem
token: '!secret duckdnstoken'
domains:
  - '!secret duckdnsurl'
aliases: []
seconds: 300
```

## Traceback/Error logs

Relevant logs from the companion app are included in this issue: https://github.com/home-assistant/android/issues/1709

## Additional information

I can try to open a pull-request with relevant changes but i anticipate that the exact implementation might need some discussion, thus opening this issue first.
