### ISSUE TITLE
DuckDNS: exited 7 when setting ipv6 config value

### ISSUE THREAD

**Issue by inverse** [home-assistant/addons#2344]
### Describe the issue you are experiencing

Following the documentation and setting ipv6 config value to something like

```yaml
ipv6: https://ipv6.text.wtfismyip.com
```

The addon fails to boot and exits 7. See below for full log output.

Full config 

```yaml
lets_encrypt:
  accept_terms: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  algo: secp384r1
token: <redacted>
domains:
  - <redacted>
aliases: []
seconds: 300
ipv6: https://ipv6.text.wtfismyip.com
```

Without this configuration everything is fine.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Duck DNS

### What is the version of the add-on?

1.14.0

### Steps to reproduce the issue

1.Add `ipv6` config
2. boot

### Anything in the add-on logs that might be useful for us?

```txt
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
# INFO: Using main config file /data/workdir/config
+ Account already registered!
[cmd] /run.sh exited 7
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

### Additional information

I noticed when trying to invoke the command used to get ipv6 in the ssh addon it fails too with the same exit code

```
[core-ssh ~]$ curl -s -m 10 https://ipv6.text.wtfismyip.com/
[core-ssh ~]$ echo $?
7
```

I have IPv6 + my LAN too and other addons like Adguard seem to be working just fine.
