### ISSUE TITLE
Add-on "MariaDB" does not support !secret

### ISSUE THREAD

**Issue by GerdRuetten** [home-assistant/addons#2398]
### Describe the issue you are experiencing

The Add-On "MariaDB" does not support !secret in his configuration and throw an error

Confuguration:
```
databases:
  - !secret mariadb_database
logins:
  - password: !secret mariadb_password
    username: !secret mariadb_username
rights:
  - database: !secret mariadb_database
    username: !secret mariadb_username
```
Error:
`Fehler beim Speichern der Add-on-Konfiguration, Unknown secret 'mariadb_database' in MariaDB (core_mariadb). Got {'databases': ['!secret mariadb_database'], 'logins': [{'password': '!secret mariadb_password', 'username': '!secret mariadb_username'}], 'rights': [{'database': '!secret mariadb_database', 'username': '!secret mariadb_username'}]}
`

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Debian

### Which add-on are you reporting an issue with?

MariaDB

### What is the version of the add-on?

2.4.0

### Steps to reproduce the issue

1. Go in the Add-On - Configuration
2. Try to set the parameters via !secret
3. Try to save it
...

### Additional information

My secret.yaml looks like:

```
mariadb_database: homeassistant
mariadb_password: MySuperStrongPassword
mariadb_username: MyUser

```

**Comment by GerdRuetten** [comment]
bumb

**Comment by ludeeus** [comment]
Your log say that the secret `mariadb_database` was not found.
Secrets are read every 60s.

**Comment by everssmarthome** [comment]
I'm also having this problem. I have waited longer than 60 seconds. I have restarted HA. The config just cannot read secrets it seems.

**Comment by everssmarthome** [comment]
turns out you have to quote the secrets like this.

```
databases:
  - homeassistant
logins:
  - password: '!secret mariadb_pass'
    username: '!secret mariadb_user'
rights:
  - database: homeassistant
    username: '!secret mariadb_user'
```
