### ISSUE TITLE
DuckDNS doesn't update IP

### ISSUE THREAD

**Issue by loeffelpan** [home-assistant/addons#2428]
### Describe the issue you are experiencing

Addon does not update IP.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Duck DNS

### What is the version of the add-on?

1.14.0

### Steps to reproduce the issue

Set up addon with some config and let it go.
Warning as above is thrown every five minutes.

Here is my config:
```
aliases: []
domains:
  - ha-ra.duckdns.org
lets_encrypt:
  accept_terms: true
  algo: secp384r1
  certfile: fullchain.pem
  keyfile: privkey.pem
seconds: 300
token: ...
```

### Anything in the add-on logs that might be useful for us?

```txt
[17:49:05] WARNING: KO
```

### Additional information

Something similar is mentioned in #2387.
In my case there are no upper case letters, but maybe it's related to the dash?
