### ISSUE TITLE
Unable to use without usr/pwd after upgrading from 6.0.2 to 6.1.1

### ISSUE THREAD

**Issue by bigboban** [home-assistant/addons#2483]
### Describe the issue you are experiencing

I have no usr/pwd config. This is config in plugin:

```
logins: []
require_certificate: false
certfile: fullchain.pem
keyfile: privkey.pem
customize:
  active: true
  folder: mosquitto
anonymous: true
```

2 main clients:

- zigbee2mqtt
- HA core

After upgrading communication is broken. Error messages are in addon log - see below.

I think this could be source of problem:

`Remove mosquitto-auth-plug and replace with mosquitto-go-auth 1.8.2`

But i don't see any info about breaking changes.

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Other (e.g., Raspbian/Raspberry Pi OS/Fedora)

### Which add-on are you reporting an issue with?

Mosquitto broker

### What is the version of the add-on?

6.1.1

### Steps to reproduce the issue

1. Use "no usr/pwd" (anon) config of plugin
2. upgrade to 6.1.1
3. errors in log, mqtt communication broken
...

### Anything in the add-on logs that might be useful for us?

```txt
1651863797: New connection from xx.xx.xx.xx:33658 on port 1883.
error: received null username or password for unpwd check
1651863797: Client <unknown> disconnected, not authorised.
```
