### ISSUE TITLE
DNSMASQ v1.5.0 just fails to start

### ISSUE THREAD

**Issue by Masterz69** [home-assistant/addons#2636]
### Describe the issue you are experiencing

After upgrade 1.4.4.->1.5.0. it fails to start:
![image](https://user-images.githubusercontent.com/15225823/187291415-c62d1322-84f6-45b7-abb0-fca083277219.png)

By docs - cname is optional config, as well Configuration page does not provide possibility to define CNAME's.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Dnsmasq

### What is the version of the add-on?

1.5.0

### Steps to reproduce the issue

Do upgrade 1.4.4. -> 1.5.0 and tried to start it.

### Anything in the Supervisor logs that might be useful for us?

```txt
Nothing in Supervisor logs about add-on.
```

### Anything in the add-on logs that might be useful for us?

```txt
No add-on log available.
```

### Additional information

v1.4.4. add-on config is very simple:
```
defaults:
  - 192.168.1.6
forwards: []
hosts:
  - host: ha.local
    ip: 192.168.1.11
<couple hosts defined>
services: []
```
