### ISSUE TITLE
MariaDB !secret not working in UI, only in yaml

### ISSUE THREAD

**Issue by AleXSR700** [home-assistant/addons#2663]
### Describe the issue you are experiencing

When user or password are entered as `!secret`, the addon throws an error and does not let you save the new settings.
If you enter them in yaml, the exact same `!secret` entries work.

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Debian

### Which add-on are you reporting an issue with?

MariaDB

### What is the version of the add-on?

2.5.1

### Steps to reproduce the issue

See above

**Comment by mdegat01** [comment]
I just tried it and it seemed to work fine for me both ways. What are you entering in the UI?

**Comment by AleXSR700** [comment]
I used
```
databases:
  - homeassistant
logins:
  - username: !secret mariadb_homeassistant_user
    password: !secret mariadb_homeassistant_password
rights:
  - username: !secret mariadb_homeassistant_user
    database: homeassistant
```
