### ISSUE TITLE
Add-On deCONZ: double click event id changed from 2002 to 2004

### ISSUE THREAD

**Issue by ekt-** [home-assistant/addons#2734]
### Describe the issue you are experiencing

I notice that the ids of some events have suddenly changed value since the last version.
eg: tradfri shoirtcut button double click is now

```
event_type: deconz_event
data:
  id: tradfri_shortcut_button
  unique_id: 14:b4:57:ff:fe:44:97:b2
  event: 2004
  device_id: 750ce08c6f3ed26546172a57412981c3
origin: LOCAL
time_fired: "2022-11-01T16:06:00.318898+00:00"
context:
  id: 01GGSZ2GVY8BB8Q3MPY4EB74G6
  parent_id: null
  user_id: null
```

until yesterday this event had id 2002. is it a wanted change? if yes, I missed the braking change in the release notes

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

deCONZ

### What is the version of the add-on?

6.17.0

### Steps to reproduce the issue

Install 6.17.0
double click deconz_event is 2004
Install 6.15.0 
double click deconz_event is 2002

### System Health information

There are currently no repairs available

### Anything in the Supervisor logs that might be useful for us?

```txt
no errors
```

### Anything in the add-on logs that might be useful for us?

```txt
no errors
```
