### ISSUE TITLE
Whisper Docker Image with CUDA 12

### ISSUE THREAD

**Issue by oatsvine** [home-assistant/addons#3296]
### Describe the issue you are experiencing

I'd like the whisper Docker image to be based on a recent image with CUDA and other dependencies. 

It seems reasonable that someone motivated enough to setup a self-hosted whisper runner would also want to benchmark it with their GPU. Otherwise, there's no way to assess whether the performance is good enough to be usable. This leads to unfortunate time sinking hacks: https://www.tarball.ca/posts/home-assistant-wyoming-whisper-cuda-gpu-support/

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Whisper

### What is the version of the add-on?

https://hub.docker.com/layers/rhasspy/wyoming-whisper/latest/images/sha256-8ab98d933feb64b09882574303119176d0dda61d1db2a2fc6972016a1699944c?context=explore

### Steps to reproduce the issue

1. Configure nvidia
```
  wyoming-whisper:
    image: rhasspy/wyoming-whisper
    container_name: whisper
    ports:
      - "10300:10300"
    volumes:
      - ./hass/whisper:/data
    command: [ "--model", "medium-int8", "--language", "en", "--beam-size", "5", "--device", "cuda" ]
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - utility
                - compute
```
2. Invoke Assist, which fails
4. The whisper logs show libcudnn, libcublas, etc libraries not found. The link in the description explains the problem.
...

### System Health information

N/A
