### ISSUE TITLE
Let's Encrypt: dns_directadmin_url is required error

### ISSUE THREAD

**Issue by defaultsecurity** [home-assistant/addons#3335]
### Describe the issue you are experiencing

The addon won't start anymore. The log says "dns_directadmin_url is required" The parameter is correctly set in the config. The addons was working before the update to 5.0.1.

### What type of installation are you running?

Home Assistant Supervised

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Let's Encrypt

### What is the version of the add-on?

5.0.1

### Steps to reproduce the issue

1. Start addon
2. Addons stops

### System Health information

-

### Anything in the Supervisor logs that might be useful for us?

```txt
-
```

### Anything in the add-on logs that might be useful for us?

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/file-structure.sh
cont-init: info: /etc/cont-init.d/file-structure.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun lets-encrypt (no readiness notification)
s6-rc: info: service legacy-services successfully started
[23:21:06] INFO: Selected DNS Provider: dns-directadmin
[23:21:06] INFO: Use propagation seconds: 60
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Renewing an existing certificate for ****.*********.***
{}: dns_directadmin_url is required
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Additional information

Config:

```
domains:
  - ****.******.***
email: *****@*******.***
keyfile: privkey.pem
certfile: fullchain.pem
challenge: dns
dns:
  provider: dns-directadmin
  directadmin_url: https://***************
  directadmin_username: *********
  directadmin_password: *********************************
```
