### ISSUE TITLE
z-wave js - Script for adjusting the blind tilt (Fibaro Roller Shutter FGR223) does not respect the delay

### ISSUE THREAD

**Issue by maisen20** [home-assistant/addons#3394]
### Describe the issue you are experiencing

Hello everyone

I would like to tilt my blinds only minimally, so that the slats of the blinds are almost completely closed.

I have created a script for this, but unfortunately the delay is not adhered to. No matter how small the delay is (or completely removed), it always takes longer (approx. 1s). If I increase the delay, e.g. 2s or more, the timeout is correctly observed.

Unfortunately, my Fibaro roller shutters (FGR223) do not support precise positioning and tilting. Therefore I have to realize this with short “up” and “down” commands.

```
alias: Tilt Cover
sequence:
  - service: cover.open_cover
    data: {}
    target:
      device_id: f5a4ea4fdfff4680a21ae3cf384edbe8
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 200
  - service: cover.stop_cover
    data: {}
    target:
      device_id: f5a4ea4fdfff4680a21ae3cf384edbe8
mode: single
icon: mdi:window-shutter-open
```

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Z-Wave JS

### What is the version of the add-on?

0.4.3

### Steps to reproduce the issue

1. Make script as descripted above
2. Execute and check whether the delay has been observed

## System Information

version | core-2023.12.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.58-haos-raspi
arch | aarch64
timezone | Europe/Zurich
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.33.0
Stage | running
Available Repositories | 1367
Downloaded Repositories | 12

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.2
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.0
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 57.8 GB
disk_used | 7.2 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (17.0.1), Terminal & SSH (9.8.1), Z-Wave JS (0.4.3), File editor (5.7.0), Music Assistant BETA (2.0.0b80), Z-Wave JS UI (3.0.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 8
views | 11
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 28. Dezember 2023 um 14:16
-- | --
current_recorder_run | 5. Januar 2024 um 17:34
estimated_db_size | 403.14 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Anything in the add-on logs that might be useful for us?

```txt
2024-01-06T09:13:28.152Z CNTRLR   [Node 006] Timed out while waiting for a response from the node (ZW0201)
2024-01-06T09:13:29.629Z CNTRLR   [Node 006] Timed out while waiting for a response from the node (ZW0201)
```
