### ISSUE TITLE
Cannot pass `length_scale` option to piper 

### ISSUE THREAD

**Issue by Ramblurr** [home-assistant/addons#3792]
### Describe the issue you are experiencing

You cannot send the `length_scale` option when invoking TTS as a service to cause the resulting audio to be spoken faster or slower.

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

Piper

### What is the version of the add-on?

1.5.2

### Steps to reproduce the issue

1. Try this

```yaml
  - service: tts.speak
    data:
      message: "this is a test"
      cache: false
      media_player_entity_id: media_player.office_test
      options:
        voice: en_US-libritts-high
        speaker: 0
        length_scale: 0.5
    target:
      entity_id: tts.piper
```

Result: 

```
Failed to perform the action tts.speak. Invalid options found: ['length_scale']
```

## System Information

version | core-2024.9.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.46-haos
arch | x86_64
timezone | Europe/Vienna
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4999
Installed Version | 1.32.1
Stage | running
Available Repositories | 1429
Downloaded Repositories | 20

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.10.0
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 30.8 GB
disk_used | 20.5 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.4.1), File editor (5.8.0), Studio Code Server (5.17.1), Advanced SSH & Web Terminal (19.0.0), AppDaemon (0.16.6), ESPHome (2024.8.3), Whisper (2.1.2), Piper (1.5.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 14
views | 7
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 5, 2024 at 5:51 AM
-- | --
current_recorder_run | October 7, 2024 at 4:47 PM
estimated_db_size | 1611.76 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

**Comment by Ramblurr** [comment]
still relevant

**Comment by shadshack** [comment]
Same issue for me, and my YAML is the same formatting.

```yaml
data:
  cache: true
  message: "false"
  media_player_entity_id: media_player.office_display
  options:
    voice: en-us-amy-low
    length_scale: 0.75
target:
  entity_id: tts.piper
action: tts.speak
```
