### ISSUE TITLE
VLC Player file selection from script

### ISSUE THREAD

**Issue by TheSimTek** [home-assistant/addons#3978]
### Describe the issue you are experiencing

Need a little help finalizing the code for a script run from a button. Using the VLC add on I want to select a file to play each time the script runs but so far cannot get it to work.

Hopefully someone can help correct where I have gone wrong or correct an issue with VLC player.  I have noticed that I can manually load the file to play but after the second time it runs I get an unsuccessful login notification from an IP address that the VLC player is on.  Hoping this script will fix this issue.

This is the script -

```
alias: Audio VLC Player
description: VLC Telnet will play the audio file selected
triggers: []
conditions: []
actions:
  - type: turn_on
    device_id: 3fa33906516*********************
    entity_id: 0c5e1d42542*********************
    domain: switch
    enabled: true
  - action: media_player.media_play
    target:
      entity_id: media_player.vlc_telnet
    data:
      media_content_id: /media/AudioFile.wav
      media_content_type: audio/wav
  - action: media_player.volume_set
    data:
      volume_level: 0.22
    target:
      entity_id: media_player.vlc_telnet
  - action: whatsapp.send_message
    metadata: {}
    data:
      clientId: default
      to: 1203632**********@g.us
      body:
        text: Someone has entered the building
  - delay:
      hours: 0
      minutes: 2
      seconds: 00
      milliseconds: 0
  - action: media_player.media_stop
    metadata: {}
    data: {}
    target:
      entity_id: media_player.vlc_telnet
  - type: turn_off
    device_id: 3fa33906516*********************
    entity_id: 0c5e1d42542*********************
    domain: switch
    enabled: true
mode: single
```

I am getting this error -

`extra keys not allowed @ data['media_content_id']. Got None extra keys not allowed @ data['media_content_type']. Got None`

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### Which add-on are you reporting an issue with?

CEC Scanner

### What is the version of the add-on?

0.3.0

### Steps to reproduce the issue

1.
2.
3.
...

## System Information

version | core-2025.4.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.13.2
os_name | Linux
os_version | 6.12.20-haos
arch | x86_64
timezone | Australia/Sydney
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.5
Stage | running
Available Repositories | 1627
Downloaded Repositories | 20

</details>

<details><summary>Solcast Solar</summary>

can_reach_server | ok
-- | --

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 15.1
-- | --
update_channel | stable
supervisor_version | supervisor-2025.03.4
agent_version | 1.7.2
docker_version | 28.0.4
disk_total | 116.7 GB
disk_used | 17.6 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (12.5.0), Mosquitto broker (6.5.0), Terminal & SSH (9.16.0), eWeLink Smart Home (1.4.3), Tailscale (0.25.0), ESPHome Device Builder (2025.3.3), Frigate (0.15.0), Firefox (1.5.0), go2rtc (1.9.9), Music Assistant Server (2.5.0), Whatsapp (1.3.5), Network UPS Tools (0.14.1), VLC (0.3.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 7
-- | --
resources | 13
views | 12
mode | storage

</details>

<details><summary>Network Configuration</summary>

adapters | lo (disabled), eno1 (enabled, default, auto), hassio (disabled), docker0 (disabled), vethd85cd84 (disabled), veth2df07ef (disabled), veth7e74986 (disabled), veth1e597c4 (disabled), vethf0d56a7 (disabled), veth8370782 (disabled), vethf9e653d (disabled), vetha194653 (disabled), veth92e81cf (disabled), veth1f8d0d8 (disabled), veth2286cb1 (disabled), veth82e2a7b (disabled), veth7de8b2e (disabled)
-- | --
ipv4_addresses | lo (127.0.0.1/8), eno1 (192.168.1.69/24), hassio (172.30.32.1/23), docker0 (172.30.232.1/23), vethd85cd84 (), veth2df07ef (), veth7e74986 (), veth1e597c4 (), vethf0d56a7 (), veth8370782 (), vethf9e653d (), vetha194653 (), veth92e81cf (), veth1f8d0d8 (), veth2286cb1 (), veth82e2a7b (), veth7de8b2e ()
ipv6_addresses | lo (::1/128), eno1 (fe80::fd32:2984:7543:71/64), hassio (fe80::8dd:61ff:fe11:9e6/64), docker0 (fe80::44f9:9cff:fe98:d021/64), vethd85cd84 (fe80::c8c9:81ff:fe97:f483/64), veth2df07ef (fe80::3c6d:a9ff:fe41:fe6f/64), veth7e74986 (fe80::141b:77ff:fe84:5976/64), veth1e597c4 (fe80::bc88:c8ff:fe05:c805/64), vethf0d56a7 (fe80::c0e1:f5ff:fe6f:c563/64), veth8370782 (fe80::9c7b:feff:fe16:1d74/64), vethf9e653d (fe80::5c6a:e3ff:fed9:a1fb/64), vetha194653 (fe80::58:bfff:fe81:dc66/64), veth92e81cf (fe80::8433:ddff:fe33:24d2/64), veth1f8d0d8 (fe80::3c52:cdff:fe37:3887/64), veth2286cb1 (fe80::d880:cff:fe78:b833/64), veth82e2a7b (fe80::14b9:6ff:fe1a:6f11/64), veth7de8b2e (fe80::6c9d:2bff:fe5b:c48a/64)
announce_addresses | 192.168.1.69, fe80::fd32:2984:7543:71

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 24 March 2025 at 01:20
-- | --
current_recorder_run | 4 April 2025 at 07:26
estimated_db_size | 1826.80 MiB
database_engine | sqlite
database_version | 3.48.0

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Anything in the Supervisor logs that might be useful for us?

```txt

```

### Anything in the add-on logs that might be useful for us?

```txt

```
